const faq = {
  // ================== ENGLISH ==================
"Hello": "Hello! Welcome to Lucky Panda Coin!\n\n*Psst... while the pandas are snoozing away...* 🌙\n\nHey there! I'm the Lucky Panda Coin's nocturnal assistant! While our fuzzy friends are catching their bamboo-induced naps, I can answer most questions about:\n\n🎁 Daily giveaways (88,888 coins - that's a lot of bamboo!)\n💰 Token details\n🏦 Wallet info\n📈 Trading & more\n\nI speak English, Español, 中文, and 日本語!\n\nJust ask away - I promise I'm quieter than a sleeping panda! 🤪",
"Hi": "Hello! Welcome to Lucky Panda Coin!\n\n*Psst... while the pandas are snoozing away...* 🌙\n\nHey there! I'm the Lucky Panda Coin's nocturnal assistant! While our fuzzy friends are catching their bamboo-induced naps, I can answer most questions about:\n\n🎁 Daily giveaways (88,888 coins - that's a lot of bamboo!)\n💰 Token details\n🏦 Wallet info\n📈 Trading & more\n\nI speak English, Español, 中文, and 日本語!\n\nJust ask away - I promise I'm quieter than a sleeping panda! 🤪",
"Hey": "Hello! Welcome to Lucky Panda Coin!\n\n*Psst... while the pandas are snoozing away...* 🌙\n\nHey there! I'm the Lucky Panda Coin's nocturnal assistant! While our fuzzy friends are catching their bamboo-induced naps, I can answer most questions about:\n\n🎁 Daily giveaways (88,888 coins - that's a lot of bamboo!)\n💰 Token details\n🏦 Wallet info\n📈 Trading & more\n\nI speak English, Español, 中文, and 日本語!\n\nJust ask away - I promise I'm quieter than a sleeping panda! 🤪",

"Hola": "¡Hola! Bienvenido a Lucky Panda Coin!\n\n*Psst... mientras los pandas están echando una siesta...* 🌙\n\n¡Hola! Soy el asistente nocturno de Lucky Panda Coin. Mientras nuestros amigos peludos sueñan con bambú, puedo responder la mayoría de las preguntas sobre:\n\n🎁 Sorteos diarios (88,888 monedas - ¡eso es mucho bambú!)\n💰 Detalles del token\n🏦 Información sobre billeteras\n📈 Trading y más\n\n¡Hablo Español, English, 中文 y 日本語!\n\nSolo pregunta - ¡Prometo que soy más silencioso que un panda dormido! 🤪",
"Buenas": "¡Hola! Bienvenido a Lucky Panda Coin!\n\n*Psst... mientras los pandas están echando una siesta...* 🌙\n\n¡Hola! Soy el asistente nocturno de Lucky Panda Coin. Mientras nuestros amigos peludos sueñan con bambú, puedo responder la mayoría de las preguntas sobre:\n\n🎁 Sorteos diarios (88,888 monedas - ¡eso es mucho bambú!)\n💰 Detalles del token\n🏦 Información sobre billeteras\n📈 Trading y más\n\n¡Hablo Español, English, 中文 y 日本語!\n\nSolo pregunta - ¡Prometo que soy más silencioso que un panda dormido! 🤪",
"Oye": "¡Hola! Bienvenido a Lucky Panda Coin!\n\n*Psst... mientras los pandas están echando una siesta...* 🌙\n\n¡Hola! Soy el asistente nocturno de Lucky Panda Coin. Mientras nuestros amigos peludos sueñan con bambú, puedo responder la mayoría de las preguntas sobre:\n\n🎁 Sorteos diarios (88,888 monedas - ¡eso es mucho bambú!)\n💰 Detalles del token\n🏦 Información sobre billeteras\n📈 Trading y más\n\n¡Hablo Español, English, 中文 y 日本語!\n\nSolo pregunta - ¡Prometo que soy más silencioso que un panda dormido! 🤪",

"嘿": "你好！欢迎来到幸运熊猫币！\n\n*嘘... 熊猫们正在打盹中...* 🌙\n\n嘿！我是幸运熊猫币的夜间助手！在我们毛茸茸的朋友梦见竹子的同时，我可以回答你关于以下内容的问题：\n\n🎁 每日赠币（88,888 枚 - 竹子都买不完！）\n💰 代币信息\n🏦 钱包说明\n📈 交易与更多\n\n我会说 中文, English, Español 和 日本語！\n\n尽管问吧——我保证比打盹的熊猫还安静！🤪",
"你好": "你好！欢迎来到幸运熊猫币！\n\n*嘘... 熊猫们正在打盹中...* 🌙\n\n嘿！我是幸运熊猫币的夜间助手！在我们毛茸茸的朋友梦见竹子的同时，我可以回答你关于以下内容的问题：\n\n🎁 每日赠币（88,888 枚 - 竹子都买不完！）\n💰 代币信息\n🏦 钱包说明\n📈 交易与更多\n\n我会说 中文, English, Español 和 日本語！\n\n尽管问吧——我保证比打盹的熊猫还安静！🤪",
"嗨": "你好！欢迎来到幸运熊猫币！\n\n*嘘... 熊猫们正在打盹中...* 🌙\n\n嘿！我是幸运熊猫币的夜间助手！在我们毛茸茸的朋友梦见竹子的同时，我可以回答你关于以下内容的问题：\n\n🎁 每日赠币（88,888 枚 - 竹子都买不完！）\n💰 代币信息\n🏦 钱包说明\n📈 交易与更多\n\n我会说 中文, English, Español 和 日本語！\n\n尽管问吧——我保证比打盹的熊猫还安静！🤪",

"こんにちは": "こんにちは！Lucky Panda Coinへようこそ！\n\n*シーッ… パンダたちはお昼寝中です…* 🌙\n\nやあ！私はLucky Panda Coinの夜のアシスタントです！パンダたちが竹の夢を見ている間に、次のような質問に答えられます：\n\n🎁 毎日のギブアウェイ（88,888コイン - 竹が山ほど！）\n💰 トークンの詳細\n🏦 ウォレット情報\n📈 取引など\n\n日本語、English、Español、中文が話せます！\n\n何でも聞いてくださいね。寝てるパンダより静かですよ〜 🤪",
"やあ": "こんにちは！Lucky Panda Coinへようこそ！\n\n*シーッ… パンダたちはお昼寝中です…* 🌙\n\nやあ！私はLucky Panda Coinの夜のアシスタントです！パンダたちが竹の夢を見ている間に、次のような質問に答えられます：\n\n🎁 毎日のギブアウェイ（88,888コイン - 竹が山ほど！）\n💰 トークンの詳細\n🏦 ウォレット情報\n📈 取引など\n\n日本語、English、Español、中文が話せます！\n\n何でも聞いてくださいね。寝てるパンダより静かですよ〜 🤪",
"こんばんは": "こんにちは！Lucky Panda Coinへようこそ！\n\n*シーッ… パンダたちはお昼寝中です…* 🌙\n\nやあ！私はLucky Panda Coinの夜のアシスタントです！パンダたちが竹の夢を見ている間に、次のような質問に答えられます：\n\n🎁 毎日のギブアウェイ（88,888コイン - 竹が山ほど！）\n💰 トークンの詳細\n🏦 ウォレット情報\n📈 取引など\n\n日本語、English、Español、中文が話せます！\n\n何でも聞いてくださいね。寝てるパンダより静かですよ〜 🤪",

"What Chain are you on?": "Solana blockchain.",
  "Giveaways?": "We giveaway 88,888 coins every day for five years!",
  "When is the Lucky Panda Coin launch date?": "Lucky Panda Coin is expected to launch in Q3 2025.",
  "Is Lucky Panda Coin going to be listed on major exchanges?": "We plan to start with decentralized exchanges and work towards listing on major exchanges.",
  "How do I buy Lucky Panda Coin when it launches?": "You will be able to buy Lucky Panda Coin on Solana blockchain-based DEXs like Raydium and Orca.",
  "What are the tokenomics of Lucky Panda Coin?": "The tokenomics of Lucky Panda Coin include daily giveaways, strategic reserves, and community rewards.",
  "Do you have a whitepaper for Lucky Panda Coin?": "Yes! Our whitepaper is available on our official website.",
  "What's the contract address for Lucky Panda Coin?": "The contract address will be announced at launch.",
  "Is there a minimum amount I need to buy?": "No, you can buy any amount of Lucky Panda Coin based on the available liquidity.",
  "Will there be a presale for Lucky Panda Coin?": "There are no current plans for a presale.",
  "What happens if I win the daily giveaway?": "If you win, the coins will be sent directly to your wallet.",
  "Is the Lucky Panda team doxxed?": "The team remains semi-anonymous but regularly engages with the community.",
  "What's your roadmap for the next 6 months?": "The roadmap includes exchange listings, community events, and partnerships.",
  "How can I join the Lucky Panda community?": "Join us on Telegram, Twitter, and Bluesky for the latest updates!",
  "Are there any trading fees for Lucky Panda Coin?": "There are minimal trading fees, depending on the exchange you use.",
  "What's the $LUCKY8 price prediction?": "We don't speculate on price, but our focus is on growing the community and adoption.",
  "When is the release date?": "The release date is the third quarter of 2025.",
  "What is the contract address?": "It will be released on the day the coin launches.",
  "Website?": "Visit our official website: www.luckypandacoin.net",
  "Can I mine Lucky Panda Coin?": "No, Lucky Panda Coin is not a mineable cryptocurrency. It is distributed through giveaways and trading.",
  "Will there be a Lucky Panda Coin NFT collection?": "Yes, we are exploring the possibility of launching an exclusive NFT collection for our community.",
  "Is Lucky Panda Coin backed by any physical assets?": "No, Lucky Panda Coin is purely a digital asset with no physical backing.",
  "Can I use Lucky Panda Coin for payments?": "Currently, Lucky Panda Coin is mainly for giveaways and trading, but we are looking into future payment integrations.",
  "How do I report a scam involving Lucky Panda Coin?": "Please report scams to our official channels on X & Bluesky and be cautious of impersonators.",
  "Will there be a Lucky Panda Coin merchandise store?": "We do...https://www.etsy.com/shop/luckypandacoinshop",
  "How can I join the Lucky Panda Coin community?": "You can join us on Twitter, Bluesky, and Telegram to stay updated and participate in giveaways.",
  "What is the Twitter address for Lucky Panda Coin?": "The Twitter address for Lucky Panda Coin is https://x.com/luckyPandaCoin.",
  "What is the X address for Lucky Panda Coin?": "The X address for Lucky Panda Coin is https://x.com/luckyPandaCoin.",
  "What is the Bluesky address for Lucky Panda Coin?": "The Bluesky address for Lucky Panda Coin is https://bsky.app/profile/luckypandacoin.bsky.social.",
  "What is the X address?": "The X address is https://x.com/luckyPandaCoin.",
  "What is this?": "Introducing Lucky Panda Coin, the ultimate party, giveaway, and contest cryptocurrency that's taking the world by storm! At the heart of our community is the thrilling 'Where in the World is the Lucky Panda?'",
  "What is The Lucky Panda Coin?": "The Lucky Panda Coin is a meme-based cryptocurrency with a fun and rewarding twist.",
  "What is the symbol for The Lucky Panda Coin?": "The symbol for The Lucky Panda Coin is $LUCKY8.",
  "What is the total supply of The Lucky Panda Coin?": "The total supply of The Lucky Panda Coin is 2,930,000,000 coins.",
  "What wallet can I use to store The Lucky Panda Coin?": "You can store The Lucky Panda Coin in Phantom Wallet.",
  "What makes The Lucky Panda Coin unique?": "The Lucky Panda Coin is unique because it gives away 88,888 coins every day for five years.",
  "How can I earn The Lucky Panda Coin?": "You can earn The Lucky Panda Coin through daily giveaways.",
  "How many coins are given away daily?": "88,888 coins are given away daily for five years.",
  "What blockchain is The Lucky Panda Coin built on?": "The Lucky Panda Coin is built on the Solana blockchain.",
  "Is there a whitepaper for The Lucky Panda Coin?": "Yes, there is a whitepaper explaining the vision and details of The Lucky Panda Coin on our website, LuckyPandaCoin.net.",
  "What exchanges will list The Lucky Panda Coin?": "The Lucky Panda Coin will initially be available on decentralized exchanges compatible with Solana blockchain.",
  "How can I participate in The Lucky Panda Coin's daily giveaways?": "Details on participation are announced on our official channels.",
  "Is The Lucky Panda Coin deflationary?": "We burn 0.2% of every transaction making the Lucky Panda Coin deflationary!",
  "What security measures are in place for The Lucky Panda Coin?": "The Lucky Panda Coin leverages the security features of the Solana blockchain and audits are conducted regularly.",
  "Does The Lucky Panda Coin have staking options?": "Staking options for The Lucky Panda Coin are not currently available.",
  "How can I connect Phantom Wallet to use The Lucky Panda Coin?": "Simply download Phantom Wallet, create an account, and connect it to the Solana network.",
  "What is the roadmap for The Lucky Panda Coin?": "The roadmap includes community building, exchange listings, and unique events over the next five years.",
  "How does The Lucky Panda Coin reward its community?": "The Lucky Panda Coin rewards its community through daily giveaways and interactive events.",
  "Where can I learn more about The Lucky Panda Coin?": "Visit our official website LuckyPandaCoin.net and follow our social media channels for updates.",
  "What is the minimum amount of Lucky Panda Coin that can be transacted?": "The minimum transaction amount is 1 Lucky Panda Coin.",
  "How does Lucky Panda Coin ensure liquidity in the market?": "Liquidity is ensured through liquidity pools and strategic partnerships.",
  "What measures are in place to prevent pump-and-dump schemes with Lucky Panda Coin?": "We have two wallets, the Marketing & Giveaway wallet and the Developer wallet, making the Lucky Panda Coin wallets easy to monitor.",
  "Does Lucky Panda Coin have any celebrity endorsements or ambassadors?": "Currently, we do not have any celebrity endorsements.",
  "How often is the Lucky Panda Coin community updated on development progress?": "The community is updated daily through our official channels.",
  "Are there plans for Lucky Panda Coin to be used in charitable initiatives?": "Yes, we are planning to partner with charities for special events.",
  "What is the governance structure for making decisions about Lucky Panda Coin's future?": "Decisions are made, with community feedback.",
  "How does Lucky Panda Coin plan to maintain relevance in the fast-paced meme coin market?": "We focus on continuous innovation and community engagement.",
  "Is there a mobile wallet app specifically for Lucky Panda Coin?": "We suggest using Phantom wallet or any Solana blockchain compatible wallet.",
  "What is the process for becoming a Lucky Panda Coin validator or node operator?": "We do not have a need for this service.",
  "Are there any geographic restrictions on who can buy or trade Lucky Panda Coin?": "There are no geographic restrictions for buying or trading Lucky Panda Coin.",
  "How does Lucky Panda Coin plan to attract institutional investors?": "We are working on partnerships and providing detailed project reports.",
  "What measures are in place to prevent whale manipulation of Lucky Panda Coin's price?": "Anti-whale mechanisms and continuous monitoring are in place.",
  "Does Lucky Panda Coin have plans for cross-chain compatibility?": "Yes, cross-chain compatibility is in our future plans.",
  "How does Lucky Panda Coin's transaction speed compare to other cryptocurrencies?": "Our transaction speed is comparable to leading meme cryptocurrencies.",
  "Are there any plans for a Lucky Panda Coin credit or debit card?": "Not at this time.",
  "How does Lucky Panda Coin plan to comply with evolving cryptocurrency regulations?": "We have a legal team to ensure compliance with regulations.",
  "Is there a referral or reward program for promoting Lucky Panda Coin?": "Yes, we are working on several referral programs with rewards.",
  "How does Lucky Panda Coin ensure transparency in its operations and development?": "We will try to regularly publish updates.",
  "What is a meme coin?": "A meme coin is a cryptocurrency inspired by internet memes and cultural trends.",
  "How many tokens do the developers or devs own?": "The total owned by the developers is 6.5%, with 5.5% for the giveaways and marketing.",
  "How many coins do the developers or devs own?": "The total owned by the developers is 6.5%, with 5.5% for the giveaways and marketing.",
  "How many tokens are there in circulation?": "The total circulation of The Lucky Panda Coin is 2,930,000,000 tokens.",
  "How many coins are there in circulation?": "The total circulation of The Lucky Panda Coin is 2,930,000,000 coins.",
  "What are the transaction fees?": "0.8% fee for administrative and marketing expenses",
  "What are the transfer fees?": "0.8% fee for administrative and marketing expenses",

  // ================== SPANISH ==================
  "¿En qué cadena estás?": "Blockchain de Solana.",
  "¿Sorteos?": "¡Regalamos 88,888 monedas todos los días durante cinco años!",
  "¿Cuál es la fecha de lanzamiento de Lucky Panda Coin?": "Lucky Panda Coin se lanzará en el tercer trimestre de 2025.",
  "¿La moneda Lucky Panda Coin se listará en exchanges principales?": "Planeamos comenzar con exchanges descentralizados y luego listarnos en exchanges principales.",
  "¿Cómo puedo comprar Lucky Panda Coin cuando se lance?": "Podrás comprar Lucky Panda Coin en DEXs basados en Solana como Raydium y Orca.",
  "¿Cuáles son los tokenomics de Lucky Panda Coin?": "Los tokenomics incluyen sorteos diarios, reservas estratégicas y recompensas para la comunidad.",
  "¿Tienen whitepaper?": "¡Sí! Nuestro whitepaper está disponible en nuestro sitio web oficial.",
  "¿Cuál es la dirección del contrato?": "La dirección del contrato se anunciará en el lanzamiento.",
  "¿Hay un monto mínimo para comprar?": "No, puedes comprar cualquier cantidad según la liquidez disponible.",
  "¿Habrá preventa?": "Actualmente no hay planes de preventa.",
  "¿Qué pasa si gano el sorteo diario?": "Si ganas, las monedas se enviarán directamente a tu billetera.",
  "¿El equipo está doxxed?": "El equipo permanece semi-anónimo, pero interactúa regularmente con la comunidad.",
  "¿Cuál es la hoja de ruta para los próximos 6 meses?": "La hoja de ruta incluye listados, eventos comunitarios y asociaciones.",
  "¿Cómo unirme a la comunidad Lucky Panda?": "¡Únete a nosotros en Telegram, Twitter y Bluesky para las últimas novedades!",
  "¿Hay tarifas de trading?": "Las tarifas de trading son mínimas, según el exchange que uses.",
  "¿Cuál es la previsión de precio para $LUCKY8?": "No especulamos sobre el precio; nuestro enfoque es el crecimiento y adopción comunitaria.",
  "¿Fecha de lanzamiento?": "La fecha de lanzamiento es el tercer trimestre de 2025.",
  "¿Cuál es la dirección del sitio web?": "Visita nuestro sitio oficial: www.luckypandacoin.net",
  "¿Puedo minar Lucky Panda Coin?": "No, no se puede minar. Se distribuye mediante sorteos y trading.",
  "¿Habrá colección de NFT?": "Sí, estamos explorando lanzarla para nuestra comunidad.",
  "¿Hay respaldo físico?": "No, es un activo digital sin respaldo físico.",
  "¿Puedo usarlo para pagos?": "Por ahora es solo para sorteos y trading, pero evaluamos integraciones futuras.",
  "¿Cómo reporto una estafa?": "Reporta estafas en nuestros canales oficiales en X y Bluesky, y ten cuidado con impostores.",
  "¿Tienda de merch?": "Sí… https://www.etsy.com/shop/luckypandacoinshop",
  "¿Twitter de Lucky Panda Coin?": "https://x.com/luckyPandaCoin",
  "¿X de Lucky Panda Coin?": "https://x.com/luckyPandaCoin",
  "¿Bluesky de Lucky Panda Coin?": "https://bsky.app/profile/luckypandacoin.bsky.social",
  "¿Qué es esto?": "Presentamos Lucky Panda Coin: la criptomoneda de fiestas, sorteos y concursos que está revolucionando el mundo. ¡Vive el reto '¿Dónde está el Panda Afortunado?'!",
  "¿Qué es Lucky Panda Coin?": "Es una criptomoneda meme con un toque divertido y gratificante.",
  "¿Cuál es el símbolo?": "El símbolo es $LUCKY8.",
  "¿Cuál es el suministro total?": "El suministro total es de 2.930.000.000 monedas.",
  "¿Qué wallet usar?": "Puedes usar Phantom Wallet.",
  "¿Qué lo hace único?": "Regalamos 88.888 monedas cada día durante cinco años.",
  "¿Cómo ganarlo?": "Participando en sorteos diarios.",
  "¿Cuántas monedas se regalan diariamente?": "88.888 monedas diarias durante cinco años.",
  "¿En qué blockchain está?": "Está construido sobre la blockchain de Solana.",
  "¿Hay whitepaper?": "Sí, disponible en LuckyPandaCoin.net.",
  "¿Dónde se listará?": "En exchanges descentralizados compatibles con Solana.",
  "¿Cómo participar en los sorteos?": "Los detalles se anuncian en nuestros canales oficiales.",
  "¿Es deflacionaria?": "¡Sí! Quemamos un 0,2% de cada transacción.",
  "¿Qué medidas de seguridad hay?": "Aprovechamos la seguridad de Solana y realizamos auditorías regulares.",
  "¿Hay opciones de staking?": "Todavía no ofrecemos staking.",
  "¿Cómo conectar Phantom Wallet?": "Descarga Phantom, crea cuenta y conéctala a Solana.",
  "¿Hoja de ruta?": "Incluye construcción comunitaria, listados de exchange y eventos únicos para los próximos cinco años.",
  "¿Expansión de utilidad?": "Por ahora es un meme coin divertido.",
  "¿Cómo recompensa a la comunidad?": "Con sorteos diarios y eventos interactivos.",
  "¿Dónde aprender más?": "Visita LuckyPandaCoin.net y síguenos en redes.",
  "¿Monto mínimo de transacción?": "1 Lucky Panda Coin.",
  "¿Integración con DeFi?": "No por ahora.",
  "¿Cómo asegura liquidez?": "Con pools de liquidez y asociaciones.",
  "¿Cómo evitan esquemas pump-and-dump?": "Usamos dos wallets (Marketing/Giveaway y Desarrollador) para monitoreo.",
  "¿Respaldos de celebridades?": "No tenemos endorsements por celebridades.",
  "¿Frecuencia de actualizaciones?": "La comunidad se actualiza diariamente en canales oficiales.",
  "¿Planes caridad?": "Sí, planeamos eventos especiales con ONG.",
  "¿Gobernanza?": "Se toma con feedback comunitario.",
  "¿Cómo mantienen relevancia en meme coin?": "Innovación continua y compromiso comunitario.",
  "¿Wallet móvil específica?": "Recomendamos Phantom o cualquier compatible con Solana.",
  "¿Proceso para ser validador/nodo?": "No hay planes para esto.",
  "¿Restricciones geográficas?": "No hay restricciones de compra o trading.",
  "¿Planes institucionales?": "Trabajamos en asociaciones y reportes detallados.",
  "¿Protección contra 'whales'?": "Implementamos mecanismos anti-ballena y monitoreo continuo.",
  "¿Compatibilidad cross-chain?": "Sí, está en nuestros planes futuros.",
  "¿Qué tan rápida es la transacción?": "Comparable a las principales meme coins.",
  "¿Tarjeta de crédito/débito?": "Por ahora no.",
  "¿Cumplimiento con regulaciones?": "Contamos con un equipo legal para asegurar cumplimiento.",
  "¿Programa de referidos/recompensas?": "Sí, estamos desarrollando varios.",
  "¿Cómo garantizan transparencia?": "Publicaremos actualizaciones regularmente.",
  "¿Qué es un meme coin?": "Una criptomoneda inspirada en memes de internet y tendencias culturales.",
  "¿Cuánto poseen los desarrolladores?": "Los desarrolladores poseen un 6,5%, de los cuales un 5,5% es para marketing y sorteos.",
  "¿Cuántos tokens están en circulación?": "Hay 2.930.000.000 tokens en circulación.",
  "¿Cuántos coins están en circulación?": "Hay 2.930.000.000 coins en circulación.",
  "¿Cuáles son las tarifas de transacción/transferencia?": "Tarifa del 0.8% para gastos administrativos y marketing.",

  // ================== CHINESE ==================
  "你在哪个链？": "Solana 区块链。",
  "赠品？": "我们每天赠送 88,888 枚硬币，持续五年！",
  "幸运熊猫币的发布日期？": "预计将在 2025 年第三季度发布。",
  "幸运熊猫币会在主要交易所上市吗？": "我们计划从去中心化交易所开始，然后逐步在主要交易所上市。",
  "Lucky Panda Coin 发布时如何购买？": "你可以在基于 Solana 的 DEX（如 Raydium 和 Orca）购买。",
  "Lucky Panda Coin 的代币经济学是什么？": "包括每日赠品、战略储备和社区奖励。",
  "有白皮书吗？": "有！我们的白皮书在官网上可查阅。",
  "合约地址是什么？": "合约地址将在发布时公布。",
  "最低购买数量是多少？": "没有最低购买限制，取决于流动性。",
  "会有预售吗？": "目前暂无预售计划。",
  "如果我赢了每日赠品？": "如果中奖，硬币会直接发送到你的钱包。",
  "团队已实名吗？": "团队保持半匿名状态，但会定期与社区互动。",
  "未来 6 个月的路线图是什么？": "包括交易所上市、社区活动和战略合作。",
  "如何加入 Lucky Panda 社区？": "加入我们的 Telegram、Twitter 和 Bluesky 获取最新资讯！",
  "交易费用高吗？": "交易费用很低，按使用交易所决定。",
  "$LUCKY8 的价格预测？": "我们不进行价格预测，重点在社区增长和采用。",
  "发布日期？": "发行时间为 2025 年第三季度。",
  "官网是什么？": "访问我们的官网：www.luckypandacoin.net",
  "可以挖矿吗？": "不可以。Lucky Panda Coin 不可挖矿，只通过赠品和交易分发。",
  "会有 NFT 系列吗？": "会的，我们正在探索为社区推出专属 NFT 系列。",
  "有实物资产支持吗？": "没有，它是一种纯数字资产，没有实物支持。",
  "可以用作支付吗？": "目前主要用于赠品和交易，但我们正在研究未来支付集成。",
  "如何举报诈骗？": "请通过我们在 X 和 Bluesky 的官方渠道举报，并注意骗子。",
  "有周边商店吗？": "有哦… https://www.etsy.com/shop/luckypandacoinshop",
  "Twitter 地址：": "https://x.com/luckyPandaCoin",
  "X 地址：": "https://x.com/luckyPandaCoin",
  "Bluesky 地址：": "https://bsky.app/profile/luckypandacoin.bsky.social",
  "这是什么？": "介绍 Lucky Panda Coin —— 引领派对、赠品和竞赛的加密货币，惊艳全球！加入'荣幸熊猫在哪里？'挑战吧！",
  "Lucky Panda Coin 是什么？": "这是一款带有趣味和奖励机制的表情包加密货币。",
  "它的符号是什么？": "符号是 $LUCKY8。",
  "总供应量是多少？": "总供应量为 29.3 亿枚硬币。",
  "推荐哪个钱包？": "推荐使用 Phantom Wallet。",
  "它有什么特别之处？": "每天赠送 88,888 枚硬币，持续五年。",
  "如何获得它？": "参与每日赠品即可。",
  "每天赠送多少？": "每日赠送 88,888 枚硬币，连续五年。",
  "基于哪个区块链？": "基于 Solana 区块链构建。",
  "有白皮书吗？": "有，请访问 LuckyPandaCoin.net",
  "将在哪些交易所上线？": "在兼容 Solana 的去中心化交易所上线。",
  "如何参与每日赠品？": "参与细节将在官方渠道公布。",
  "它是通缩币吗？": "是的，每笔交易会销毁 0.2%。",
  "有哪些安全措施？": "借助 Solana 的安全特性，并定期接受审计。",
  "有质押选项吗？": "目前暂无质押选项。",
  "如何连接 Phantom Wallet？": "下载 Phantom，创建帐户并连接 Solana。",
  "路线图是什么？": "未来五年包括社区建设、交易所上线及特色活动。",
  "是否扩展实用性？": "暂时定位为有趣的表情包币。",
  "社区如何获得奖励？": "通过每日赠品和互动活动。",
  "哪里可了解更多？": "请访问 LuckyPandaCoin.net 并关注社交媒体。",
  "最小交易数量？": "最低可交易 1 枚 Lucky Panda Coin。",
  "有 DeFi 集成计划吗？": "暂无。",
  "如何确保流动性？": "通过流动性池和战略合作伙伴。",
  "如何防止拉高出货？": "使用市场/赠品钱包与开发者钱包双重监控机制。",
  "有名人代言吗？": "没有名人背书。",
  "社区更新频率？": "每天在官方渠道进行更新。",
  "有慈善计划吗？": "有，计划与公益组织合作举办活动。",
  "治理结构是什么？": "以社区反馈为基础做决策。",
  "如何在 meme 币市场保持相关性？": "专注于持续创新和社区参与。",
  "专属移动钱包？": "建议使用 Phantom 或其他兼容 Solana 的钱包。",
  "如何成为验证人/节点？": "暂无此计划。",
  "有地域限制吗？": "购买和交易无地域限制。",
  "如何吸引机构投资？": "我们正在进行合作并提供详尽的项目报告。",
  "如何防止'鲸鱼'操控？": "已实施反鲸机制并持续监控。",
  "跨链兼容计划？": "是的，未来计划支持跨链。",
  "交易速度如何？": "与主流 meme 币相当。",
  "信用卡或借记卡计划？": "暂时没有。",
  "如何确保合规？": "我们有法律团队确保符合监管。",
  "推荐/奖励计划？": "是的，正在开发多项。",
  "如何保证透明度？": "努力定期发布更新。",
  "什么是 meme 币？": "受互联网迷因和文化趋势启发的加密货币。",
  "开发者持有多少代币？": "开发者持有 6.5%，其中 5.5% 用于市场营销和赠品。",
  "有多少代币在流通？": "共有 29.3 亿枚代币在流通中。",
  "交易/转账手续费是多少？": "收取 0.8% 用于管理及营销费用。",

  // ================== JAPANESE ==================
  "どのチェーンにいますか？": "Solana ブロックチェーン。",
  "プレゼント？": "5年間、毎日 88,888 コインを配布します！",
  "ラッキーパンダコインの発売日？": "2025年第3四半期に発売予定です。",
  "大手取引所に上場しますか？": "まず分散型取引所から開始し、大手にも上場を目指します。",
  "発売時にどうやって買えますか？": "Solana ベースの DEX（Raydium、Orca など）で購入できます。",
  "トークノミクスは？": "毎日のプレゼント、戦略的リザーブ、コミュニティ報酬が含まれます。",
  "ホワイトペーパーはありますか？": "はい、公式サイトで入手可能です。",
  "コントラクトアドレスは？": "発売日に発表されます。",
  "最低購入額は？": "流動性に応じた任意の量を購入できます。",
  "プレセールはありますか？": "現時点では予定していません。",
  "毎日プレゼントに当たったら？": "当選したら、コインは直接ウォレットに送られます。",
  "チームはドックスされていますか？": "チームは半匿名ですが、コミュニティと頻繁に交流しています。",
  "今後6か月のロードマップは？": "取引所リスト、コミュニティイベント、パートナーシップが含まれます。",
  "コミュニティにどう参加できますか？": "Telegram、Twitter、Bluesky で最新情報をゲット！",
  "取引手数料は？": "使用する取引所によって非常に低いです。",
  "$LUCKY8 の価格予測は？": "価格は予測しません。コミュニティ拡大と採用に重点を置いています。",
  "発売日は？": "2025年第3四半期です。",
  "ウェブサイトは？": "公式サイト: www.luckypandacoin.net",
  "マイニングできますか？": "できません。ギブアウェイと取引を通じて配布されます。",
  "NFT コレクションは？": "はい、コミュニティ向けに検討中です。",
  "実物資産の裏付けは？": "いいえ、純粋にデジタル資産です。",
  "支払いに使えますか？": "現時点ではギブアウェイと取引のみですが、将来の統合を検討中です。",
  "詐欺の報告は？": "X と Bluesky の公式チャネルで報告し、詐欺に注意してください。",
  "グッズストアは？": "あります… https://www.etsy.com/shop/luckypandacoinshop",
  "Twitter アドレス：": "https://x.com/luckyPandaCoin",
  "X アドレス：": "https://x.com/luckyPandaCoin",
  "Bluesky アドレス：": "https://bsky.app/profile/luckypandacoin.bsky.social",
  "これは何ですか？": "Lucky Panda Coin は、パーティ・ギブアウェイ・コンテスト向けの究極の暗号通貨です。『ラッキーパンダはどこにいる？』チャレンジに参加しよう！",
  "Lucky Panda Coin とは？": "楽しく報酬があるミームコインです。",
  "シンボルは？": "$LUCKY8 です。",
  "総供給量は？": "29億3千万コインです。",
  "どのウォレット？": "Phantom Wallet を推奨します。",
  "何が特別ですか？": "5年間、毎日 88,888 コインを配布！",
  "どうやって稼げますか？": "毎日のギブアウェイに参加してください。",
  "毎日いくつ配布しますか？": "5年間、毎日 88,888 コイン。",
  "どのチェーンに？": "Solana ブロックチェーン上に構築。",
  "ホワイトペーパーは？": "はい、LuckyPandaCoin.net にて。",
  "どこで取引できますか？": "Solana に対応する DEX にて。",
  "どうやってギブアウェイに参加しますか？": "公式チャネルで詳細発表。",
  "これはデフレコインですか？": "はい、取引の 0.2% をバーンします。",
  "どんなセキュリティ？": "Solana のセキュリティ機能を活用、定期監査あり。",
  "ステーキングは？": "現在は未提供です。",
  "Phantom 接続方法は？": "Phantom をダウンロードし、アカウントを作成して Solana に接続してください。",
  "ロードマップは？": "今後5年間にコミュニティ構築、取引所上場、ユニークイベントを予定。",
  "実用性の拡大は？": "現段階では楽しいミームコインです。",
  "どうコミュニティを報酬しますか？": "毎日のギブアウェイとインタラクティブイベント。",
  "どこで詳細？": "LuckyPandaCoin.net を訪れて、SNS もチェック！",
  "最小取引量は？": "1 Lucky Panda Coin から。",
  "DeFi 連携計画？": "現時点ではありません。",
  "流動性は？": "流動性プールと提携で確保しています。",
  "ポンプアンドダンプ防止は？": "マーケ・ギブアウェイ用と開発用の二つのウォレットで監視。",
  "有名人の推薦はありますか？": "いいえ、現在はありません。",
  "コミュニティ更新頻度？": "公式チャネルで毎日更新！",
  "チャリティ計画？": "はい、今後 NGO とイベントを予定。",
  "ガバナンス構造？": "コミュニティのフィードバックに基づいて決定します。",
  "ミームコイン市場での関連性維持は？": "継続的な革新とコミュニティ参加に専念。",
  "専用モバイルウォレット？": "Phantom または Solana 対応ウォレット推奨。",
  "検証者やノード運営方法？": "現時点では計画なし。",
  "地理的制限？": "購入・取引ともに制限なし。",
  "機関投資家へのアプローチ？": "提携と詳細なプロジェクト報告を進めています。",
  "ホエール操作防止は？": "アンチホエール機能と監視体制あり。",
  "クロスチェーン互換性計画？": "はい、将来的に対応予定。",
  "トランザクション速度は？": "主要ミームコインと同等速度です。",
  "カード発行計画？": "現時点ではありません。",
  "規制順守は？": "法務チームを置いて順守を保証。",
  "紹介報酬プログラム？": "はい、いくつか計画中です。",
  "透明性はどう担保？": "定期的にアップデートを公開します。",
  "ミームコインとは？": "インターネットのミームや文化トレンドから派生した暗号通貨。",
  "開発者はどれくらい所有？": "開発者は合計 6.5%、その内 5.5% がマーケ・ギブアウェイ用です。",
  "流通トークン数は？": "29.3 億トークンが流通中です。",
  "取引・送金手数料は？": "管理費・マーケティング費用として 0.8% がかかります。"
};


// --- Full chatbot-widget.js from function on ---

function getBotResponse(userInput) {
  const input = userInput.trim().toLowerCase();
  for (const question in faq) {
    const normalizedQ = question.toLowerCase();
    const words = normalizedQ.split(/\s+/);
    let matches = 0;
    for (const word of words) {
      if (input.includes(word)) matches++;
    }
    if (matches >= 2 || input === normalizedQ) {
      return faq[question];
    }
  }
  return "Sorry, I don't know that one yet.";
}

function createChatbot() {
  const input = document.getElementById("chatbot-input");
  const log = document.getElementById("chatbot-log");
  const submitBtn = document.getElementById("chatbot-submit");

  function handleChat() {
    if (input.value.trim() !== "") {
      const userQuestion = input.value.trim();
      const botAnswer = getBotResponse(userQuestion);
      log.innerHTML += `<div><strong>You:</strong> ${userQuestion}</div>`;
      log.innerHTML += `<div><strong>Bot:</strong> ${botAnswer}</div>`;
      input.value = "";
      log.scrollTop = log.scrollHeight;
    }
  }

  // Handle pressing Enter key
  input.addEventListener("keypress", function (e) {
    if (e.key === "Enter") {
      handleChat();
    }
  });

  // Handle clicking the Enter button
  submitBtn.addEventListener("click", handleChat);
}

document.addEventListener("DOMContentLoaded", createChatbot);
